### ISSUE TITLE
READMEs start barge with no-aquarius & no-elastic, yet bots need these

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#241] opened 2023-10-17 15:28 UTC
### The problem

All the READMEs specify to start barge including the arguments `--no-aquarius --no-elasticsearch`.

Yet this causes failure, because some bots need aquarius or elasticsearch.

This includes `pdr-publisher` unable to publish feeds.

Without feeds published, all the other bots that need feeds then fail too.

Another example is pdr-trader failing; see example in [comment](https://github.com/oceanprotocol/pdr-backend/issues/241#issuecomment-1766695684) below.

### Solution

Remove  `--no-aquarius --no-elasticsearch` from all the READMEs.

**Comment by idiom-bytes** [comment] 2023-10-17 15:48
Even after having pdr-publisher deploy feeds + updating subgraph, the `predictoor/main.py` keeps not finding published feeds.
![image](https://github.com/oceanprotocol/pdr-backend/assets/69865342/b901cd46-c434-4fed-bacb-2640e5f0f9f9)

**Comment by trentmc** [comment] 2023-10-17 15:57
> readme.md skips creating venv python -m venv venv

No. It's in the "install pdr" step

Re the second problem: I have this same problem. I thought it was just a MacOS x Docker thing. It's definitely an issue.

@idiom-bytes this ticket's title & description is too vague. Since it's *two* problems, it's far better if you report it as *two* github issues, each with a very specific title & description. Can you do that now please? (Or, since the first issue re venv is already taken care of, simply remove all discussion of that, and re-orient the existing github issue)

**Comment by idiom-bytes** [comment] 2023-10-17 16:08
Hi Trent, I was hoping to create 1 ticket for each doc.

In other words:
1. Complete each README e2e
2. Capture all the issues inside 1 ticket per README

**Comment by trentmc** [comment] 2023-10-17 18:08
Make reach github issue have exactly one problem please

**Comment by trentmc** [comment] 2023-10-18 08:13
@idiom-bytes recall that I've had problems with barge too. I had given up, chalking it to MacOS issues. But your problem inspired me to try something: when starting barge, don't include `--no-aquarius --no-elasticsearch`. 

So tried that. Specifically:

**First, I did all the steps in barge.md's install section:**

That is: In barge console:
```console
# Grab repo
git clone https://github.com/oceanprotocol/barge
cd barge

# Switch to predictoor branch of barge repo
git checkout predictoor

# Clean up previous Ocean-related dirs & containers (optional but recommended) 
rm -rf ~/.ocean
./cleanup.sh
docker system prune -a --volumes
```

And, I started Docker. (Needed for MacOS.)

**Then, I did the steps from predictoor local/local setup:**

With a twist: the call to start.sh doesn't have `--no-aquarius --no-elasticsearch`. 

That is: In a different console:
```console
# set ganache block time to 5 seconds, try increasing this value if barge is lagging
export GANACHE_BLOCKTIME=5

#run barge with all bots except predictoor
./start_ocean.sh --no-provider --no-dashboard --predictoor --with-thegraph --with-pdr-trueval --with-pdr-trader --with-pdr-publisher --with-pdr-dfbuyer
```

**Here are my results**

- The log showed that it was able to publish contracts
- I confirmed that by following directions in subgraph.md: going to the browser, opening subgraph page, and pasting in the query. [Here's the url](http://localhost:9000/subgraphs/name/oceanprotocol/ocean-subgraph/graphql?query=query%7B%0A++predictContracts%7B%0A++++id%0A++++token%7B%0A++++++name%0A++++%7D%0A++++subscriptions%28orderBy%3A+expireTime+orderDirection%3Adesc+first%3A10%29%7B%0A++++++user+%7B%0A++++++++id%0A++++++%7D%0A++++++expireTime%0A++++%7D%0A++++slots%28orderBy%3A+slot+orderDirection%3Adesc+first%3A10%29%7B%0A++++++slot%0A++++++roundSumStakesUp%0A++++++roundSumStakes%0A++++++predictions%28orderBy%3A+timestamp+orderDirection%3Adesc%29%7B%0A++++++++stake%0A++++++++user+%7B%0A++++++++++id%0A++++++++%7D%0A++++++++timestamp%0A++++++++payout%7B%0A++++++++++payout%0A++++++++++predictedValue%0A++++++++++trueValue%0A++++++++%7D%0A++++++%7D%0A++++++trueValues%7B%0A++++++++trueValue%0A++++++%7D%0A++++%7D%0A++%7D+%0A%7D). It successfully output all the feeds.
- BUT - from the log - most of the agents encountered issues and then exited. 
[Here's the full log](https://github.com/oceanprotocol/pdr-backend/files/12999050/log.txt). You'll see errors in the last portion of the log.
- I considered opening a separate issue, but I want to dovetail with you on this @idiom-bytes . 

cc @trizin @alexcos20 -- please read this comment and tell me if there's anything I could do differently to maybe make this work. (Perhaps there's hope for Barge in my Mac setup after all?)

**Comment by trentmc** [comment] 2023-10-18 12:52
While `address.json` is there, there is no entry for `development` is not.

This is a failure on barge's part, afaik.

**Comment by trentmc** [comment] 2023-10-21 10:27
I fixed this in https://github.com/oceanprotocol/pdr-backend/commit/a34db07f3db88e36e3262c1ddd1fa41c8d32adb7, 3 days ago.

(Somehow I'd accidentally reopened the issue)

Closing.

**Closed by trentmc** 2023-10-21 10:27 UTC
Labels: Type: Bug
