### ISSUE TITLE
Give BasePredictoorAgent memory and make it not submit multiple times

### ISSUE THREAD

**Issue by idiom-bytes** [oceanprotocol/pdr-backend#320] opened 2023-11-09 22:38 UTC
### Problem
Right now predictoor_agent registers they predicted the epoch, but.... 
- It doesn't check if it's already submitted
- It doesn't cache it
- It submits multiple times

Rather, the user should configure `s_until_epoch_end` to set the maximum time window to guarantee/submit a prediction before the epoch ends, only once per epoch prediction/trade.

### DoD:
- [ ] Update base_predictoor_agent (and therefore all predictoor agents) such that it caches + checks if submitted already

**Comment by trentmc** [comment] 2023-11-10 07:55
This "issue" is _not_ an issue. It's by design.

The design is: keep submitting every few seconds until no time left. Each submission may have a bit more information than the previous one, therefore a bit better model. 

Closing this issue. If you feel otherwise, please reopen and we can discuss.

**Closed by trentmc** 2023-11-10 07:55 UTC
Labels: Type: Enhancement
